apiVersion: v1
kind: Service
metadata:
  name: simple-webserver-lb-svc
  namespace: hpa-example
  labels:
    app: simple-webserver
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-webserver
